[package]
name = "hacker-website"
version = "0.1.0"
authors = ["elsehow <yes@cosmopol.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
url = "2.1.0"
serde_yaml = "0.8"
url_serde = "0.2.0"